baseURL: "https://niklasschneeb.github.io/"
title: Wie schön muss Krise aussehen?
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Startseite
          url: /
          weight: 1
        - name: Thesisarbeit
          url: /thesisarbeit/
          weight: 2
        - name: Tags
          url: /tags/
          weight: 3 
        - name: Glossar
          url: /glossar/
          weight: 4       
        - name: Quellenverzeichnis
          url: /quellenverzeichnis/
          weight: 5
        - name: Impressum
          url: /impressum/
          weight: 6

params:
    description: "Beschreibung"
    author: Autor
    DateFormat: "January  2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["thesisarbeit","quellenverzeichnis","impressum"]
    ShowToc: false
    disableScrollToTop: false
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: "Wie schön muss Krise aussehen? –
          <br>
          Ein gestalterischer **Blick** auf die Optimierung im Katastrophenschutz"
          subtitle: "<br>
          Krisen und Naturkatastrophen sind meist ebenso individuell wie unvorhersehbar. Keine Sturmflut ist wie die andere, kein Erdbeben gleicht dessen Vorgänger. Genau wie die Individualität der Katastrophen muss sich auch Gestaltung auf die vorherrschenden Situationen anpassen können und auf alle Eventualitäten vorbereitet sein.
          <br><br>
          In meiner Arbeit untersuche ich die Auswirkungen und Folgen von Naturkatastrophen und weiteren Großgefahrenlagen unter dem Aspekt des Bevölkerungsschutzes. Anhand der erarbeiteten Problemstellen entwickle ich mit Hilfe von Gestaltungsmechaniken Lösungsansätze, welche das Krisenmanagement nachhaltig stärken, um bei kommenden Krisen umfangreicher vorbereitet zu sein und zielgerichteter Hilfe leisten zu können. Die Themenschwerpunkte Sichtbarkeit, Navigation und Orientierung nehmen dabei eine besondere Rolle ein.
          <br><br>
          Aus den Erkenntnissen, die ich durch meine ausführliche Recherche erhalten habe, ist ist diese Abschlussarbeit entstanden. Meine Recherche dient mir bei der Erarbeitung von Lösungsansätzen als Grundlage, auf die ich während der Umsetzung gestützt habe. Bei der Umsetzung der Lösungsansätze habe ich meinen Fokus auf die Einführung eines visuellen Erscheinungsbildes und die Erarbeitung eines modularen Leit- und Informationssystems gelegt, die ich am Ende meiner Arbeit vorgestellt habe.
          <br>"
          text: Fließtext
          buttons:
            - name: Thesisarbeit
              url: /thesisarbeit/
            - name: Tags
              url: /tags/
            - name: Glossar
              url: /glossar/
            - name: Quellenverzeichnis
              url: /quellenverzeichnis/
            - name: Impressum
              url: /impressum/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

titleCaseStyle: 'none'
