title: Wie schön muss Krise aussehen?
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Startseite
          url: /config/
          weight: 1
        - name: Thesisarbeit
          url: /papers/
          weight: 2
        - name: Tags
          url: /tags/
          weight: 3        
        - name: Quellenverzeichnis
          url: /courses/
          weight: 4
        - name: Impressum
          url: /design/
          weight: 5

params:
    description: Seitentitel
    author: Autor
    googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January  2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","courses","design"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: "Wie schön muss Krise aussehen?
          <wbr><wbr>
          Ein gestalterischer **Blick** auf die Optimierung im Katastrophenschutz"
          subtitle: "(nicht final) Gerade in den letzten Jahren hat sich die Notwendigkeit für ein reibungsloses Krisenmanagement gezeigt. Es kann etwa bei der Versorgung von Geflüchteten, beim Umgang mit Pandemien, nach Naturkatastrophen oder in Kriegssituationen Leben retten. Dabei ist eine klare, verständliche Orientierung zwingend notwendig. 
          <br><br>
          Ich möchte ein barrierearmes Leitsystem erarbeiten, das auf möglichst viele Szenarien anwendbar und in Krisensituationen unkompliziert und schnell einsatzbereit ist.
          <br><br>
          Hiermit lege ich, Niklas Schneeberger, eine **Versicherung an Eides statt** ab."
          text: Fließtext
          buttons:
            - name: Thesisarbeit
              url: /papers/
            - name: Tags
              url: /tags/
            - name: Quellenverzeichnis
              url: /courses/
            - name: Impressum
              url: /design/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: Zurück-Text
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

titleCaseStyle: 'none'
